export const ipaRecordings: Record<string, string> = {
  m: "kalama/wikimedia-phoneme-audio/audio/Bilabial_nasal.ogg",
  ɱ: "kalama/wikimedia-phoneme-audio/audio/Labiodental_nasal.ogg",
  n: "kalama/wikimedia-phoneme-audio/audio/Alveolar_nasal.ogg",
  ɳ: "kalama/wikimedia-phoneme-audio/audio/Retroflex_nasal.ogg",
  ɲ: "kalama/wikimedia-phoneme-audio/audio/Palatal_nasal.ogg",
  ŋ: "kalama/wikimedia-phoneme-audio/audio/Velar_nasal.ogg",
  ɴ: "kalama/wikimedia-phoneme-audio/audio/Uvular_nasal.ogg",
  p: "kalama/wikimedia-phoneme-audio/audio/Voiceless_bilabial_plosive.ogg",
  b: "kalama/wikimedia-phoneme-audio/audio/Voiced_bilabial_plosive.ogg",
  t̼: "kalama/wikimedia-phoneme-audio/audio/Voiceless_linguolabial_stop.ogg",
  d̼: "kalama/wikimedia-phoneme-audio/audio/Voiced_linguolabial_stop.ogg",
  t̪: "kalama/wikimedia-phoneme-audio/audio/Voiceless_dental_stop.ogg",
  d̪: "kalama/wikimedia-phoneme-audio/audio/Voiced_dental_stop.ogg",
  t: "kalama/wikimedia-phoneme-audio/audio/Voiceless_alveolar_plosive.ogg",
  d: "kalama/wikimedia-phoneme-audio/audio/Voiced_alveolar_plosive.ogg",
  ʈ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_retroflex_stop.oga",
  ɖ: "kalama/wikimedia-phoneme-audio/audio/Voiced_retroflex_stop.oga",
  c: "kalama/wikimedia-phoneme-audio/audio/Voiceless_palatal_plosive.ogg",
  ɟ: "kalama/wikimedia-phoneme-audio/audio/Voiced_palatal_plosive.ogg",
  k: "kalama/wikimedia-phoneme-audio/audio/Voiceless_velar_plosive.ogg",
  g: "kalama/wikimedia-phoneme-audio/audio/Voiced_velar_plosive_02.ogg",
  q: "kalama/wikimedia-phoneme-audio/audio/Voiceless_uvular_plosive.ogg",
  ɢ: "kalama/wikimedia-phoneme-audio/audio/Voiced_uvular_stop.oga",
  ʡ: "kalama/wikimedia-phoneme-audio/audio/Epiglottal_stop.ogg",
  ʔ: "kalama/wikimedia-phoneme-audio/audio/Glottal_stop.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiceless_dental_sibilant_affricate.oga",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_dental_sibilant_affricate.oga",
  ts: "kalama/wikimedia-phoneme-audio/audio/Voiceless_alveolar_sibilant_affricate.oga",
  dz: "kalama/wikimedia-phoneme-audio/audio/Voiced_alveolar_sibilant_affricate.oga",
  tʃ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_palato-alveolar_affricate.ogg",
  dʒ: "kalama/wikimedia-phoneme-audio/audio/Voiced_palato-alveolar_affricate.ogg",
  tʂ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_retroflex_affricate.ogg",
  dʐ: "kalama/wikimedia-phoneme-audio/audio/Voiced_retroflex_affricate.ogg",
  tɕ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_alveolo-palatal_affricate.ogg",
  dʑ: "kalama/wikimedia-phoneme-audio/audio/Voiced_alveolo-palatal_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiceless_bilabial_affricate.ogg",
  pf: "kalama/wikimedia-phoneme-audio/audio/Voiceless_labiodental_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_labiodental_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_dental_non-sibilant_affricate.oga",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_dental_non-sibilant_affricate.oga",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiceless_postalveolar_non-sibilant_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_postalveolar_non-sibilant_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiceless_palatal_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_palatal_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiceless_velar_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_velar_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiceless_uvular_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_uvular_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiceless_epiglottal_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_epiglottal_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiceless_glottal_affricate.ogg",
  s: "kalama/wikimedia-phoneme-audio/audio/Voiceless_alveolar_sibilant.ogg",
  z: "kalama/wikimedia-phoneme-audio/audio/Voiced_alveolar_sibilant.ogg",
  ʃ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_palato-alveolar_sibilant.ogg",
  ʒ: "kalama/wikimedia-phoneme-audio/audio/Voiced_palato-alveolar_sibilant.ogg",
  ʂ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_retroflex_sibilant.ogg",
  ʐ: "kalama/wikimedia-phoneme-audio/audio/Voiced_retroflex_sibilant.ogg",
  ɕ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_alveolo-palatal_sibilant.ogg",
  ʑ: "kalama/wikimedia-phoneme-audio/audio/Voiced_alveolo-palatal_sibilant.ogg",
  ɸ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_bilabial_fricative.ogg",
  β: "kalama/wikimedia-phoneme-audio/audio/Voiced_bilabial_fricative.ogg",
  f: "kalama/wikimedia-phoneme-audio/audio/Voiceless_labio-dental_fricative.ogg",
  v: "kalama/wikimedia-phoneme-audio/audio/Voiced_labio-dental_fricative.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiceless_linguolabial_fricative.ogg",
  θ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_dental_fricative.ogg",
  ð: "kalama/wikimedia-phoneme-audio/audio/Voiced_dental_fricative.ogg",
  // : "kalama/wikimedia-phoneme-audio/audio/Voiceless_alveolar_non-sibilant_fricative.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_alveolar_non-sibilant_fricative.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiceless_postalveolar_non-sibilant_fricative.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_postalveolar_non-sibilant_fricative.ogg",
  ç: "kalama/wikimedia-phoneme-audio/audio/Voiceless_palatal_fricative.ogg",
  ʝ: "kalama/wikimedia-phoneme-audio/audio/Voiced_palatal_fricative.ogg",
  x: "kalama/wikimedia-phoneme-audio/audio/Voiceless_velar_fricative.ogg",
  ɣ: "kalama/wikimedia-phoneme-audio/audio/Voiced_velar_fricative.ogg",
  χ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_uvular_fricative.ogg",
  ʁ: "kalama/wikimedia-phoneme-audio/audio/Voiced_uvular_fricative.ogg",
  ħ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_pharyngeal_fricative.ogg",
  ʕ: "kalama/wikimedia-phoneme-audio/audio/Voiced_pharyngeal_fricative.ogg",
  h: "kalama/wikimedia-phoneme-audio/audio/Voiceless_glottal_fricative.ogg",
  ɦ: "kalama/wikimedia-phoneme-audio/audio/Voiced_glottal_fricative.ogg",
  w: "kalama/wikimedia-phoneme-audio/audio/Voiced_labio-velar_approximant.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Bilabial_approximant.ogg",
  ʋ: "kalama/wikimedia-phoneme-audio/audio/Labiodental_approximant.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_dental_approximant.ogg",
  ɹ: "kalama/wikimedia-phoneme-audio/audio/Alveolar_approximant.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Postalveolar_approximant.ogg",
  ɻ: "kalama/wikimedia-phoneme-audio/audio/Retroflex_Approximant2.oga",
  ɻʷ: "kalama/wikimedia-phoneme-audio/audio/Retroflex_approximant.ogg",
  j: "kalama/wikimedia-phoneme-audio/audio/Palatal_approximant.ogg",
  ɰ: "kalama/wikimedia-phoneme-audio/audio/Voiced_velar_approximant.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_Uvular_Approximant.ogg",
  ⱱ: "kalama/wikimedia-phoneme-audio/audio/Labiodental_flap.ogg",
  ɾ: "kalama/wikimedia-phoneme-audio/audio/Alveolar_tap.ogg",
  ɽ: "kalama/wikimedia-phoneme-audio/audio/Retroflex_flap.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Epiglottal_flap.oga",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiceless_bilabial_trill_with_aspiration.ogg",
  ʙ: "kalama/wikimedia-phoneme-audio/audio/Bilabial_trill.ogg",
  r̥: "kalama/wikimedia-phoneme-audio/audio/Voiceless_alveolar_trill.ogg",
  r: "kalama/wikimedia-phoneme-audio/audio/Alveolar_trill.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_postalveolar_trill.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_retroflex_trill.ogg",
  ʀ̥: "kalama/wikimedia-phoneme-audio/audio/Voiceless_uvular_trill.ogg",
  ʀ: "kalama/wikimedia-phoneme-audio/audio/Uvular_trill.ogg",
  ʜ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_epiglottal_trill.ogg",
  ʢ: "kalama/wikimedia-phoneme-audio/audio/Voiced_epiglottal_trill_2.ogg",
  tɬ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_alveolar_lateral_affricate.ogg",
  dɮ: "kalama/wikimedia-phoneme-audio/audio/Voiced_alveolar_lateral_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiceless_palatal_lateral_affricate.ogg",
  // :  "hhttps://upload.wikimedia.org/wikipedia/commons/0/02/Voiceless_velar_lateral_affricate.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_velar_lateral_affricate.ogg",
  ɬ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_alveolar_lateral_fricative.ogg",
  ɮ: "kalama/wikimedia-phoneme-audio/audio/Voiced_alveolar_lateral_fricative.ogg",
  ꞎ: "kalama/wikimedia-phoneme-audio/audio/Voiceless_retroflex_lateral_fricative.ogg",
  𝼆: "kalama/wikimedia-phoneme-audio/audio/Voiceless_palatal_lateral_fricative.ogg",
  𝼄: "kalama/wikimedia-phoneme-audio/audio/Voiceless_velar_lateral_fricative.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_velar_lateral_fricative.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_dental_lateral_approximant.ogg",
  l: "kalama/wikimedia-phoneme-audio/audio/Alveolar_lateral_approximant.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Voiced_postalveolar_lateral_approximant.ogg",
  ɭ: "kalama/wikimedia-phoneme-audio/audio/Retroflex_lateral_approximant.ogg",
  ʎ: "kalama/wikimedia-phoneme-audio/audio/Palatal_lateral_approximant.ogg",
  ʟ: "kalama/wikimedia-phoneme-audio/audio/Velar_lateral_approximant.ogg",
  // :  "kalama/wikimedia-phoneme-audio/audio/Uvular_lateral_approximant.ogg",

  ŋwiəŋ:
    "kalama/wikimedia-phoneme-audio/audio/Nguyen.ogg",
};
